- name: Get the hostname of the system
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Display the hostname
      debug:
        msg: "The hostname of this system is {{ ansible_hostname }}"

    - name: Print all extra variables
      debug:
        msg: "Extra variables: {{ lookup('env', 'extra_vars') }}"
